package ca.mohawk.jdw.shifty.clientapi.event;

/*
  I, Josh Maione, 000320309 certify that this material is my original work. 
  No other person's work has been used without due acknowledgement. 
  I have not made my work available to anyone else.

  Module: client-api
  
  Developed By: Josh Maione (000320309)
*/

public enum EventType {

    ADD_MY_SHIFT,
    REMOVE_MY_SHIFT,
    ADD_AVAILABLE_SHIFT,
    ADD_MY_SHIFT_OFFER,
    ADD_REQUEST_TO_MY_SHIFT_OFFER,
    ADD_MY_SHIFT_OFFER_REQUEST,
    REMOVE_AVAILABLE_SHIFT,
    REMOVE_MY_SHIFT_OFFER,
    REMOVE_REQUEST_FROM_MY_SHIFT_OFFER,
    REMOVE_MY_SHIFT_OFFER_REQUEST,
    ADD_MY_ACTIVITY_LOG,
    ADD_SEARCHED_ACTIVITY_LOG,
    UPDATE_REQUEST_RESPONSE_FROM_MY_SHIFT_OFFER,
    UPDATE_MY_SHIFT_OFFER_REQUEST_RESPONSE,
    ADD_PENDING_SHIFT_CHANGE,
    REMOVE_PENDING_SHIFT_CHANGE,

    OFFER_MY_SHIFT_RESPONSE,
    REQUEST_TO_TAKE_SHIFT_RESPONSE,
    CANCEL_MY_SHIFT_OFFER_RESPONSE,
    ANSWER_REQUEST_FROM_MY_SHIFT_OFFER_RESPONSE,
    CANCEL_REQUEST_TO_TAKE_SHIFT_RESPONSE,
    ANSWER_PENDING_SHIFT_CHANGE_RESPONSE,
    SEARCH_ACTIVITY_LOGS_BY_EMPLOYEE_RESPONSE
}
